### ISSUE TITLE
Sodium issue

### ISSUE THREAD

**Issue by jarezzz** [Sollace/Psychedelicraft#21]
With Sodium shaders are not working properly and only showing bare bone effects, like on shrooms you only get entity distortions and no static blocks are distorted.

**Comment by AuxCat** [comment]
I can confirm this also happens with Embeddium while running Psychedelicraft through Forgified Fabric and Connector. I tried adding Lazurite, which should support the Rendering API, but nothing seems to change. The visual effects work fine without Embeddium.

**Comment by Sollace** [comment]
The 1.21 build is tested with Sodium. I don't know if Embeddium will work though as I'd have to add explicit support for it.

It's not really an API issue so much as "I need to inject my shaders into whatever is loading them" issue. Sodium, rather than use the game's normal methods, decided they're going to write an entirely separate pipeline for compiling and loading shaders that I had to add support for.
